name: Android CI

on:
  push:
    branches: [ "master", "test-dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path:
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedAndroidTest
        
    - name: Upload Android Test Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: android-test-reports
        path: "**/build/reports/androidTests/"
    
          
    
