name: Android CI

on:
  push:
    branches: [ "master", "test-dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [28, 29, 30]
        emulator-type: [pixel, nexus]

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradle-deps-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-gradle-deps-

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        emulator-type: ${{ matrix.emulator-type }}
        script: ./gradlew connectedAndroidTest
        
    - name: Upload Android Test Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: android-test-reports
        path: "**/build/reports/androidTests/"
    
          
    
