name: Android CI

on:
  push:
    branches: [ "master", "test-dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Android SDK
      uses: actions/setup-android@v2
      with:
        sdk-version: '31.0.0'
        
    - name: Start Android emulator
      run: |
        echo "no" | avdmanager create avd --force --name "emulator" --device "pixel" --package "system-images;android-31;google_apis;x86_64"
        emulator -avd emulator -no-audio -no-window -gpu swiftshader_indirect &
      timeout-minutes: 3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build and test
      run: ./gradlew clean assembleDebug androidTest --no-build-cache --no-configure-on-demand
      
    - name: Build with Gradle
      run: ./gradlew build
