name: Android CI

on:
  push:
    branches: [ "master", "test-dev" ]
  pull_request:
    branches: [ "master" ]

env:
  GRADLE_USER_HOME: ./gradle-cache

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Set up Android environment
      uses: actions/setup-android@v2
      with:
        sdk-version: '31'
        ndk-version: '23.0.7599858'
        java-version: '1.8'
        emulator-version: '30.7.5'
        arch: x86_64

    - name: Build and test
      run: |
        ./gradlew assembleDebug
        ./gradlew testDebug
        ./gradlew connectedAndroidTest

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/reports/androidTests/connected/
